### ISSUE TITLE
Finding the configuration file

### ISSUE THREAD

**Issue by jbanety** [XiNiHa/relay-zed#1] opened 2024-12-09 13:35 UTC
Hi @XiNiHa,

I have a project like that which is a fake monorepo :
```
|
|-- ProjectA
    |-- src
        |-- source.graphql.ts
    |-- package.json
    |-- relay.config.json
|-- ProjectB 
    |-- ...
```

Relay compiler is unable to find the config file relay.config.json in a subfolder.

**Comment by XiNiHa** [comment] 2024-12-09 20:52
I've also previously looked into the same issue. The problem is that the Relay language server always tries to find the config file at PWD, and currently, the Zed extension API doesn't provide any method to configure a language server's working directory. I'll look into this issue at some point since it also impacts my usecase, but I'm not sure how long it'll take...

**Comment by jbanety** [comment] 2024-12-09 20:55
Maybe you can resolve the closest relay config and pass it as an argument?

**Comment by XiNiHa** [comment] 2024-12-09 20:59
Just realized there was a CLI argument for that 😅 I've only looked into the VSCode extension's source so didn't notice that. I'll try to make a fix for this soon!

**Comment by jbanety** [comment] 2024-12-09 21:07
Yeah. That's why I proposed that.
I tried to pass it appended to the relay bin path but this poor hack didn't worked 😅

**Comment by XiNiHa** [comment] 2024-12-09 21:44
Just tried applying the fix and realized the actual blocker was not about the config 😂

```
Config `/Users/xiniha/repos/solid-relay/./examples/ssr/relay.config.json` is invalid:
 - The `schema` configured for project `default` does not exist at `./schema.graphql`.
```

So the working directory should be changed either from the Relay side or the Zed side in order to make the language server resolve paths correctly 😵‍💫

**Comment by jbanety** [comment] 2024-12-10 06:03
If you add a cwd settings key and you do a basic `cd $cwd; relay-compiler....` ? 
Ugly but it can work. 
With cwd relative to zed workspace root ?

**Comment by XiNiHa** [comment] 2024-12-10 06:23
I should put the command into [a struct](https://docs.rs/zed_extension_api/latest/zed_extension_api/struct.Command.html) and I don't think something like that would work 😅

**Comment by jbanety** [comment] 2024-12-10 06:24
I think it might work 😁

**Comment by XiNiHa** [comment] 2024-12-10 07:15
Got it working by calling `sh -c "cd $pwd; relay-compiler ..."` 🤣

**Comment by jbanety** [comment] 2024-12-10 07:16
Haha I knew it would work!

**Comment by XiNiHa** [comment] 2024-12-10 07:23
Fixed by https://github.com/XiNiHa/relay-zed/commit/0443abe0a00c63fdf941189684e03d72b99c3b13, will release a new version soon. Thanks!

**Closed as completed by XiNiHa** 2024-12-10 07:23 UTC

**Comment by XiNiHa** [comment] 2024-12-10 07:33
Submitted an update PR at https://github.com/zed-industries/extensions/pull/1774. Hope that can be merged soon!

**Comment by juanjlunar** [comment] 2025-05-24 11:39
Hey there, I have a monorepo setup and the extension does not find the relay.config.js configuration, how did you manage that?

**Comment by XiNiHa** [comment] 2025-05-24 14:05
> Hey there, I have a monorepo setup and the extension does not find the relay.config.js configuration, how did you manage that?

You can configure the root directory option for that: https://github.com/XiNiHa/solid-relay/blob/main/.zed%2Fsettings.json#L36-L42

**Comment by juanjlunar** [comment] 2025-05-26 14:45
> > Hey there, I have a monorepo setup and the extension does not find the relay.config.js configuration, how did you manage that?
> 
> You can configure the root directory option for that: https://github.com/XiNiHa/solid-relay/blob/main/.zed%2Fsettings.json#L36-L42

Oh, I see, thank you!
